### ISSUE TITLE
Install in Squeak?

### ISSUE THREAD

**Issue by darth-cheney** [svenvc/zinc#111]
Things might have moved on enough that it's not possible, but can this be installed in Squeak? It looks like there might be some dependencies on the FileSystem API and other Pharo-specific classes, but I just wanted to be sure.

**Comment by svenvc** [comment]
Hi,

This has never been possible. Zinc itself is currently portable from Pharo 7 to Pharo 11. In the past it ran on Gemstone, maybe an old version still does.

It is not just a question of dependencies. There are subtle differences in many aspects of the language.

It is not impossible, but would require a lot of work.

HTH,

Sven
