### ISSUE TITLE
Error when using HTTP with Proxy

### ISSUE THREAD

**Issue by JanBliznicenko** [svenvc/zinc#119]
When Proxy is set up in Pharo and user attempts to connect using HTTP instead of HTTPS, it ends up with error where `ZnUrl>>#printAuthorityOn:` attempts to send message `print:` to `ZnBivalentWriteStream` that does not have that method.

I do not use Proxy myself, just forwarding the info. It can be somehow simulated if you replace condition on proxy in `ZnRequestLine>>#writeOn:` by hardcoded `true`.

Tested in Pharo 10 and 12 on Windows.

![screenshot](https://github.com/svenvc/zinc/assets/9571633/79774f3e-6375-4d9c-9b3c-a998ba4d2520)

Note that the code works when I replace `http://` by `https://`.

**Comment by svenvc** [comment]
https://github.com/svenvc/zinc/commit/3f7900abec0ad9164a4d587018899eb3247a5f12
