### ISSUE TITLE
Some Advice on serving

### ISSUE THREAD

**Issue by amroto** [svenvc/zinc#15]
can someone tell me how to serve .css, .html and .js files ? (please be specific and clear as possible)

**Comment by svenvc** [comment]
Although frameworks on top of Zinc have additional facilities, to do it directly from Zinc you would use ZnStaticFileServerDelegate

http://zn.stfx.eu/zn/zinc-http-components-paper.html#staticfileserver

https://github.com/svenvc/zinc/tree/master/repository/Zinc-FileSystem.package/ZnStaticFileServerDelegate.class

**Comment by amroto** [comment]
I am trying to serve this repo can you be more specific because I got lost in the documents https://github.com/aidarbek/angular

**Comment by svenvc** [comment]
There is documents, there is example code. The rest should come from you.

You can ask question in the Pharo community http://pharo.org/community
