### ISSUE TITLE
ZnHTTPSTests>>testGetPharoVersion and ZnClientTests>>testIfModifiedSinceNotModified  are failing

### ISSUE THREAD

**Issue by dalehenrich** [svenvc/zinc#17]
Tested both in a fresh Pharo4.0 image and in GemStone (just now porting Zodiac:).

Tests>>testGetPharoVersion fails with `client isSuccess` returning false.

ZnClientTests>>testIfModifiedSinceNotModified hangs with a connection timeout.

Haven't tried looking at PHaro-5.0, but not sure what to expect with midstream switch to spur ...

**Comment by svenvc** [comment]
Some of these tests vary, often because external hosts are acting up.

On the official dashboard everything is green: https://ci.inria.fr/pharo-contribution/job/ZincHTTPComponents/ 

They were also all green on my machine just now

I know from the standard Pharo CI jobs (that run Zn tests all the time) that some tests are less reliable, but they normally become green soon after.

**Comment by dalehenrich** [comment]
@svenvc so the question I have, is what how are those tests implemented --- presumably the tests have changed to accommodate the external hosts that are acting up ... the source in https://github.com/svenvc/zinc/blob/master/repository/Zinc-Zodiac.package/ZnHTTPSTests.class/instance/testGetPharoVersion.st uses the url: https://ci.inria.fr/pharo/job/Pharo-2.0/lastSuccessfulBuild/api/xml?xpath=/*/description and it produces a 404:

```
HTTP ERROR 404
Problem accessing /pharo/job/Pharo-2.0/lastSuccessfulBuild/api/xml. Reason:
    Not Found
Powered by Jetty://
```

presumably the passing tests are currently using a different url there --- so what url do you use?

and http://caretaker.wolf359.be/small.html times out (from https://github.com/svenvc/zinc/blob/master/repository/Zinc-Tests.package/ZnClientTests.class/instance/testIfModifiedSinceNotModified.st) so you must be using a different url there as well?

Both of these tests are consistently failing over the last two days, so this is not a timing issue.

**Comment by dalehenrich** [comment]
Pharo 5.0 results:
  - https://ci.inria.fr/pharo/job/Pharo-4.0/lastSuccessfulBuild/api/xml?xpath=/*/fullDisplayName
  - host `stfx.eu` is used instead of `wolf359.be`

**Comment by svenvc** [comment]
Yeah, sorry Dale, I didn't realize you were using older URLs.
