### ISSUE TITLE
in a znClient instance trying to get an address after posting a znEntity to the same server causes error because it doesn't reset the headers length and content type

### ISSUE THREAD

**Issue by jmari** [svenvc/zinc#20]
Entity is still there after the post call, so that it'll put the header content length and type in a wrong value. What I tried is to set the entity to nil, but then those headers are not initialized.
I've solved removing the condition "request hasEntity ifTrue: [ ]" because the method resetEntity: does a good job if entity is nil.

ZnClient>>prepareRequest
self isOneShot
ifTrue: [ request setConnectionClose ].
request hasEntity
ifTrue: [
"This is necessary because entities are often modified after first being added empty,
and a wrong content length is cached at the request level"
request resetEntity: request entity].

self sendCookies.
self prepareRequestHook 
	ifNotNil: [ :hook | hook value: request ]

**Comment by svenvc** [comment]
Hi,

I am not entirely sure I understand your issue.

Have you seen the unit test ZnClientTests>>#testGetAfterPost ?

Is that the situation your are talking about, doing a GET after a POST ?

How is your issue different ?

Sven

**Comment by jmari** [comment]
So sorry, you are right, it was solved with at znClient instance creation sending
			autoResetEntityMethods: #(HEAD DELETE GET);
Lot of thanks

**Comment by svenvc** [comment]
No problem
