### ISSUE TITLE
[Question] #fromString: of ZnMimeType?

### ISSUE THREAD

**Issue by fortizpenaloza** [svenvc/zinc#21]
Hi Sven,

I'm having an issue storing an instance of ZnMimeType as the key of a dictionary. Basically, I found that:

`ZnMimeType textPlain` 

gives me an instance with `charset=utf-8` as parameter stored into a `SmallDictionary`. But evaluating:

`ZnMimeType fromString: 'text/plain;charset=utf-8'`

the parameters are stored in a `Dictionary`.

This has the consequence that its hashes are not equal. **Is this the expected behavior?**

**Comment by svenvc** [comment]
Hi Francisco,

You are right, good catch.

https://github.com/svenvc/zinc/commit/85deae6256d53f9ea0a80cc6d462cb82b51b0e9d

===
Name: Zinc-Resource-Meta-Core-SvenVanCaekenberghe.69
Author: SvenVanCaekenberghe
Time: 20 August 2018, 4:00:10.339574 pm
UUID: 6b9b8310-4030-0d00-8eb7-d5c7087399b1
Ancestors: Zinc-Resource-Meta-Core-SvenVanCaekenberghe.68

ZnMimeType class>>#fromString: should use SmallDictionary, not Dictionary when parsing optional parameters, for compatibility with ZnMimeType>>#parameters (thx Francisco Ortiz Peñaloza)
===

Thx.

Sven
