### ISSUE TITLE
Query parameters and urls ending in /

### ISSUE THREAD

**Issue by gcotelli** [svenvc/zinc#25]
Hi Sven,
Do you know if the url obtained by asking a ZnUrl to attach a parameter is valid in case the original url ends with a `/` ? 
For example: 
`'https://google.com/search/' asZnUrl withQuery: 'q' -> 'hello'`
will produce a ZnUrl looking like `https://google.com/search/?q=hello`
To me it looks really strange ( and in this case for google it's not the same having or not the slash) 

I've simplified the example but in my case I have a url coming from some teapot route and I want to attach some queries to it and I'm getting this kind of URL.

**Comment by svenvc** [comment]
Why not

    'https://google.com/search' asZnUrl withQuery: 'q' -> 'hello'. 

    => https://google.com/search?q=hello

?

I think they are both valid, I depends on what the server expects.
But I did not check the specs.

**Comment by gcotelli** [comment]
I don't have direct control over the incoming URL. Just looked strange to me, but if it's valid syntax I think then there's no problem in adding `?`after `/`.
