### ISSUE TITLE
Zinc should allow custom server string

### ISSUE THREAD

**Issue by astares** [svenvc/zinc#27]
Details see https://pharo.fogbugz.com/f/cases/22886
and proposed fix for standard image is in https://github.com/pharo-project/pharo/pull/2215

**Comment by svenvc** [comment]
Finally https://github.com/svenvc/zinc/commit/2d52c6e4437c5a55ed0fedc6938aa9fb52ae6232 (together with many more related changes)

Example usage https://github.com/svenvc/zinc/blob/master/repository/Zinc-Tests.package/ZnServerTests.class/instance/testCustomServerString.st

The option can also be changed globally in an image (for all ZnServer instances)

ZnOptions globalDefault at: #serverString put: 'foobar server'.

More documentation will follow later (when more options/settings are converted to the new system)

This is experimental/alpha for now
