### ISSUE TITLE
Zinc should use singular and not plural for Test classes

### ISSUE THREAD

**Issue by astares** [svenvc/zinc#30]
@svenvc 

The typical pattern in Smalltalk is to use the SINGULAR form for class names, not the PLURAL.
This is also true for SUnit where you name a test on a class Foo with "FooTest" and not 
"FooTests". 

The Pharo 7.0 system already a lint rule was added lament when extension "Tests" is used instead of "Test"

Also Calypso was changed all "Tests" classes into "Test" to provide some more consistency:
https://github.com/pharo-ide/Calypso/commit/f68074839249da489621334c43782d052b9bb351

Currently Zinc is still using "Tests" for some test classes like

   ZnMimeTypeTests
   ZnUrlTests
   ...
 
and we should rename them too into 

   ZnMimeTypeTest
   ZnUrlTest
   ...

to provide some consistency in the image and also be able to integrate a release test to keep that quality level.

**Comment by svenvc** [comment]
this has been done

**Comment by astares** [comment]
Thanks!
