### ISSUE TITLE
ZnCharacterReadStream DNU binary

### ISSUE THREAD

**Issue by riverdusty** [svenvc/zinc#37]
ZnMimePart class >> fieldName: fileNamed:

converts file name (and path) to a ZnCharacterReadStream which it then tries to convert to binary, which throws error DNU.

Pharo 7 x64 on Windows 10 x64
![ZnError](https://user-images.githubusercontent.com/572263/58086960-e73cc400-7bbf-11e9-97f1-42388f644337.png)

**Comment by svenvc** [comment]
This is already fixed upstream (the Zn code in Pharo is older).

````
fieldName: fieldName fileNamed: fileName
	| mimeType size fileStream entity baseName |
	mimeType := ZnMimeType forFilenameExtension: (ZnFileSystemUtils extensionFor: fileName).
	fileStream := mimeType isBinary 
		ifTrue: [ ZnFileSystemUtils binaryReadStreamFor: fileName ] 
		ifFalse: [ ZnFileSystemUtils readStreamFor: fileName ].
	size := ZnFileSystemUtils fileSizeFor: fileName.
	(entity := ZnStreamingEntity type: mimeType length: size)
		stream: fileStream.
	baseName := ZnFileSystemUtils baseNameFor: fileName.
	^ self fieldName: fieldName fileName: baseName entity: entity
````

You can load the latest version of Zn

**Comment by astares** [comment]
Is it updated in P8 already? Why not provide a PR for P7 to fix it?

**Comment by riverdusty** [comment]
This still not back ported to Pharo7?

**Comment by svenvc** [comment]
No, an it probably never will be.
Backporting to the stable release is only done for really bad bugs.
If you care a lot about Zn, you should just load it, the external version is always newer.
