### ISSUE TITLE
Should zinc contain Beacon methods?

### ISSUE THREAD

**Issue by jecisc** [svenvc/zinc#49]
Hi Sven,

I found those methods in Zinc:
- https://github.com/svenvc/zinc/blob/master/repository/Zinc-HTTP.package/ZnLogEvent.class/instance/printOneLineOn..st
- https://github.com/svenvc/zinc/blob/master/repository/Zinc-HTTP.package/ZnLogEvent.class/instance/printOneLineContentsOn..st

I have the impression they can be removed since there is no sender in Pharo 8 and this seems to be dead code from beacon.

Do you confirm we can remove them?

**Comment by svenvc** [comment]
Hi Cyril,

I can't remember how/why this got added.
If you are sure these methods are not needed, they are candidates for removal.
But remember that Zinc tries to maintain compatibilty with older versions of Pharo.

Sven

**Comment by jecisc** [comment]
So here is the state:
- Pharo 2: Those methods are not present
- Pharo 3: Those methods are not present
- Pharo 4: Those methods are present but there is no sender in the image
- Pharo 5: Those methods are present but there is no sender in the image
- Pharo 6: Those methods are present but there is no sender in the image
- Pharo 7: Those methods are present but there is no sender in the image

I guess it's safe to remove.

**Comment by svenvc** [comment]
OK, I will remove them, thanks for checking !

**Comment by svenvc** [comment]
https://github.com/svenvc/zinc/commit/a994ba8d631c11fe41fdead63f72a46135fb0bc7
