### ISSUE TITLE
Cannot convert a ZnApplicationFormUrlEncodedEntity object to a ByteArray

### ISSUE THREAD

**Issue by jvdsandt** [svenvc/zinc#50]
In order to calculatie the MD5 hash of a http request I use the asByteArray method of ZnEntity. This method fails for ZnApplicationFormUrlEncodedEntity instances:
```
ZnApplicationFormUrlEncodedEntity new
		at: 'Param1' put: 'ValueA';
		at: 'Param2' put: 'ValueB';
		asByteArray 

`````
I think the ZnApplicationFormUrlEncodedEntity >>#writeOn: method should convert characters to bytes similar to ZnStringEntity>>#writeOn:

**Comment by svenvc** [comment]
Hi Jan,

Yes this does not work and yes this is a bug.
I have no time to commit a proper fix, but I will do so later next week.

My solution would be as follows.

I add a test 
````
ZnEntityTest>>#testApplicationUrlEncodingWriteRead
	| originalEntity bytes parsedEntity |
	originalEntity := ZnApplicationFormUrlEncodedEntity new.
	originalEntity 
		at: 'Param1' put: 'ValueA';
		at: 'Param2' put: 'ValueB'.
	bytes := originalEntity asByteArray.
	parsedEntity := ZnEntity readFrom: bytes readStream usingType: ZnMimeType applicationFormUrlEncoded andLength: bytes size.
	self assert: (parsedEntity at: 'Param1') equals: 'ValueA'.
	self assert: (parsedEntity at: 'Param2') equals: 'ValueB'.	
````
And I change 
````
ZnApplicationFormUrlEncodedEntity>>#computeRepresentation
	representation := ByteArray streamContents: [ :stream | 
		self writeRepresentationOn: (ZnBivalentWriteStream on: stream) ].
	contentLength := representation size
````
This would make your case pass.

It breaks a couple of other tests, but I now feel as if those are wronly assuming that entities can be written to a string. 

But I have to explore this a bit more before I can be 100% sure.

Thanks for reporting this issue,

Sven

**Comment by svenvc** [comment]
Should be fixed by https://github.com/svenvc/zinc/commit/546b58e36a6c48769d52b0c5196c6a657f46ded4
