### ISSUE TITLE
Please add Zinc-Server-Sent-Events package to BaselineOfZincHTTPComponents

### ISSUE THREAD

**Issue by mumez** [svenvc/zinc#54]
It is difficult to load Zinc-Server-Sent-Events package from this site for now. Please add an optional 'SSE' group to BaselineOfZincHTTPComponents.

**Comment by svenvc** [comment]
Hi,

I can do that, but honestly I can't remember anything about this.

I assume you are still using this and can confirm it still works today on recent Pharo versions ?

Sven

**Comment by mumez** [comment]
Zinc-Server-Sent-Events runs nicely on Pharo 6.1 and 7.0.5. 
It has been used about 3 years for allstocker.com. 
Our team is just starting to use Phato 8, so we are not sure it works on Pharo 8, but we can contribute if we find some problems.

**Comment by svenvc** [comment]
OK, thank you for the feedback.

Does the following work for you ? 

https://github.com/svenvc/zinc/commit/f11f1a92252a9789599a73df97f7ca60cd979a65

Do you think it would be difficult to add at least one test (in a separate package) ? You could have a look at the WebSockets implementation for inspiration.

**Comment by mumez** [comment]
Thank you for the quick response!
I've confirmed Zinc-Server-Sent-Events was successfully loaded.
```
Metacello new
  repository: 'github://svenvc/zinc/repository';
  baseline: 'ZincHTTPComponents';
  load: #('Core' 'Server-Sent-Events' ).
```

I will also try to add a unit test. 
BTW, sometimes ZnClient fails to request POST with some big payload. Our team now investigating the issue. I'll report this too.

**Comment by svenvc** [comment]
OK, great.

Thank you.
