### ISSUE TITLE
[QUESTION] Zinc-REST

### ISSUE THREAD

**Issue by jmariani** [svenvc/zinc#59]
Hi, Sven.

I see in your repository that you have a Zinc-REST package. But I cannot find it in the Pharo 8 System Browser.
Should I download your repository and overwrite Pharo's or there's any other way to get the Package?

Thank you in advance!

**Comment by svenvc** [comment]
Hi,

Yes you can just load Zn over the existing classes in Pharo 7 or higher.
```
Metacello new
  repository: 'github://svenvc/zinc/repository';
  baseline: 'ZincHTTPComponents';
  load: 'REST'.
```
Should do the trick.

Sven

**Comment by jmariani** [comment]
Thank you very much!
