### ISSUE TITLE
DELETE method should be able to have a request body

### ISSUE THREAD

**Issue by tomooda** [svenvc/zinc#65]
I found the ZnClient drops the entity when the method is set to DELETE, but the DELETE method *may* have a request body (https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE).
I think the default `autoResetEntityMethods` option should exclude `#DELETE`.

**Comment by svenvc** [comment]
Hi,

Thanks for the feedback.

This is not so clear, as the following discussion shows: https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

My summary would be: it might be allowed/tolerated but it makes almost no sense.

The autoResetEntityMethods collection is a feature of ZnClient, specifically for when re-using a ZnClient instance for multiple requests to the same server, as one typically does when talking to a REST service. In such a case, you would not want an entity from a previous request to be sent again.

If you absolutely would want to send a body with a delete, you can.

Option one is to reconfigure your ZnClient instance by calling autoResetEntityMethods:  maybe even setting it to #()

Another option is to make use of the fact that the resetting of the entity only happens in 1 specific place: after the method is set in method: 

So by using the Zn client in a specific order, you can specify an entity.

```
myClient method: #DELETE; entity: (ZnEntity text: 'text'); execute.
```

What do you think ?

Sven

**Comment by tomooda** [comment]
Thank you for your reply, Sven.
I was using ZnClient in the one-shot mode for testing a REST server like:
```
	ZnClient new
		beOneShot;
		url: 'http://localhost:10000/api/runs/1';
		entity:
			(ZnEntity
				json: (NeoJSONWriter toString: {('token' -> token)} asDictionary));
		delete.
```
where the request body carries a "token" for authentication,
and found the entity was reset by the `delete` method.
I thought to skip resetting the request body when in the one-shot mode, but it would complicate the overall behavior of ZnClinet.
So, I agree with your current design.

I'll take your suggestion to set the `DELETE` method at the top of the flow because it will make the client code more readable than mine.

Thank you very much. I'll close this issue.
