### ISSUE TITLE
Failure to download GitHub release asset after

### ISSUE THREAD

**Issue by ronsaldo** [svenvc/zinc#69]
I am having issues on downloading a GitHub release asset with zinc in Pharo 9.  I suspect this might be related to an encoding issue that might be invalidating a security token that is required for downloading the artifact after the redirect. The issue can be replicated with the following snippet on a playground:

```smalltalk
ZnClient new
	accept: 'application/octet-stream'; "Required by GitHub"
	url: 'https://api.github.com/repos/ronsaldo/abstract-gpu/releases/assets/49144132';
	followRedirects: true;
	downloadTo: 'agpu.tar.gz'
```

**Comment by svenvc** [comment]
The redirect URL seems to point to AWS S3 which seems sensitive to some URL encoding issues. I have to study this a bit more, but I have seen this before in other contexts. Either encoding is too eager or too loose, there is not one solution.

Here is my initial workspace:

```
meta := ZnClient new
	forJsonREST;
	url: 'https://api.github.com/repos/ronsaldo/abstract-gpu/releases/assets/49144132'; 
	get.

ZnClient new
	url: (meta at: 'browser_download_url');
	downloadTo: '/tmp/agpu.tar.gz';
	yourself.

ZnClient new
	url: (meta at: 'browser_download_url');
	get.

ZnLogEvent logToTranscript.

logEvents := OrderedCollection new.
ZnLogEvent announcer when: ZnLogEvent do: [ :event | logEvents add: event ].
logEvents.

redirect := ZnClient new
	dontFollowRedirects;
	url: (meta at: 'browser_download_url');
	get;
	response.
	
redirect location.
redirect headers at: #Location.
```

The last two expressions show the difference between the Location URL in unparsed/parsed form.

**Comment by svenvc** [comment]
ZnUrl's encoding strategy is currently based on https://datatracker.ietf.org/doc/html/rfc3986/#appendix-A

Specifically, the query part allows unencoded $/ and $; which are encoded by the redirect/location URL from GitHub towards AWS S3.

Zn parses the URL (correctly even if it encodes more than needed), then renders it again (without the encoding), hence it is different. The AWS S3 signature in the query part most probably depends on the URL being literally identical.

I have to read a bit more to figure out what can be done.

**Comment by ClotildeToullec** [comment]
We have a similar issue with the Moose images. They also are downloaded from a Github release.

The issue can be reproduced by trying to download a Moose image in the Pharo launcher:

> In the image creation UI: Official Distributions, Moose Suite 9.0 (development).

**Comment by svenvc** [comment]
With the following commit (update Zinc HTTP Components from this repository),

https://github.com/svenvc/zinc/commit/df181e9bae09e15d2377011aedc792323dd67070

you can specify a different encoding strategy for the query part of URLs, which makes the initial example pass
```
meta := ZnClient new
  forJsonREST;
  url: 'https://api.github.com/repos/ronsaldo/abstract-gpu/releases/assets/49144132'; 
  get.

ZnOptions globalDefault clone
  at: #queryKeyValueSafeSet put: (ZnOptions queryKeyValueSafeSet \ '/;');
  during: [
    ZnClient new
      url: (meta at: 'browser_download_url');
      get ].
```
or the equivalent with the downloadTo:

**Comment by svenvc** [comment]
It is also possible to modify the localOptions of a specific client instance:
```
ZnClient new in: [ :client |
  client localOptions at: #queryKeyValueSafeSet put: (ZnOptions queryKeyValueSafeSet \ '/;').
  client get: (meta at: 'browser_download_url') ].
```

**Comment by ronsaldo** [comment]
Thank you very much. The workaround works.

**Comment by svenvc** [comment]
Thanks for the feedback.

BTW, here is another way to customise the local options of a client, as a single expression:
```
ZnClient new 
  withOptions: [ :options |
    options at: #queryKeyValueSafeSet put: (ZnOptions queryKeyValueSafeSet \ '/;') ];
  get: (meta at: 'browser_download_url').
```

**Comment by demarey** [comment]
Hi @svenvc,

I can confirm it also works for Moose download:
```smalltalk
url := 'https://github.com/moosetechnology/Moose/releases/download/continuous/Moose9-development.zip'.

ZnClient new 
  signalProgress: true;
  url: url;
  enforceHttpSuccess: true;
  withOptions: [ :options |
    options at: #queryKeyValueSafeSet put: (ZnOptions queryKeyValueSafeSet \ '/;') ];
  downloadTo: '/tmp/moose-test'.
  ```
If I understand well, '/;' characters should not be encoded with a percent. Is it a recent change of github? Zinc worked like a charm before. How did you debug this issue? It is interesting if we have a similar problem in the future.

Thanks for the quick fix.

**Comment by svenvc** [comment]
Thank you @demarey for testing and for the feedback.

How I found the problem ? The final redirect failed, everything looked reasonable, but the URL was very complicated and I spotted a difference between the URL in the location header field and the one actually being followed. Zinc always parses and re-renders URLs. I know that this is a sensitive area.

Percent encoding can be done on a scale: very safely, encoding everything except for a small set of safe characters, which most URL parsers will accept (Zinc does), or encoding as little as possible, following the specs to the max.

Now, in this case (I guess something changed on their end), the final URL looks like an AWS S3 access with an embedded signature (AWS v4 signature). That code is very picky about encoding, formatting, ordering, etc - because it signs a very specific input. Somehow the validation code has certain expectations about the general encoding of the resulting URL. We are forced to follow (at least for now). But that is not (yet) strong enough an argument to change the default (which also came about from some trial and error, I remember I once had it on encode everything and that gave issues too).

All this has now been recorded and we will see how it goes.

**Comment by iriyak** [comment]
@joao-pedro-braz Four years may not be enough for some web services to fully comply with RFC 3986. The redirected URL contains an AWS v4 signature (AWS4-HMAC-SHA256) in the query string and returns 401 unless both `/` and `;` are percent-encoded, even though RFC 3986 doesn't require encoding these characters. While defaulting to permissive behavior would accommodate such services, it could compromise the implementation's semantic strictness regarding RFC 3986 compliance.

So as a work-around in my environment I am adding this code when starting up my Pharo VM. 😁 

```
ZnOptions globalDefault
	at: #queryKeyValueSafeSet
	put: ZnOptions queryKeyValueSafeSet \ '/;'.
```
