### ISSUE TITLE
ZnBufferedReadStream>>upToEnd returns nil when reading contents of an empty file

### ISSUE THREAD

**Issue by jbrichau** [svenvc/zinc#86]
Case: I am reading the contents of an empty (binary) file and expect to get an empty instance of `ByteArray`. I now get a `nil` as a result instead. 

This is because the `ZnBufferedReadStream>>upToEnd` returns nil for such a case.
The following test in [Grease](https://github.com/SeasideSt/Grease) illustrates the issue:
`GRPlatformTest>> testReadWriteEmptyFileInFolderBinary`

This test fails in Pharo 10 since recently only. Probably because the latest Zinc version was included recently? I have not investigated the changes. It was tested in:

`Pharo 10.0.0
Build information: Pharo-10.0.0+build.483.sha.95c615fd186704d9ae9b2d2355680145b9646774 (64 Bit)`

To reproduce in Pharo 10, load Grease
```
Metacello new
 baseline:'Grease';
 repository: 'github://SeasideSt/Grease:master/repository';
 load:'Tests'
```
and execute the test `testReadWriteEmptyFileInFolderBinary` on `GRPlatformTest`

**Comment by jbrichau** [comment]
A fix might be to change the following line https://github.com/svenvc/zinc/blob/c6f2f6174a3b0764987363d76a82165864ed8168/repository/Zinc-Character-Encoding-Core.package/ZnBufferedReadStream.class/instance/upToEnd.st#L25 
with:
```
^ result ifNil:[ self collectionSpecies new ]
```

**Comment by svenvc** [comment]
Hi @jbrichau 

Thanks for the report: this is indeed wrong. The code is also a bit weird, but somebody will have had a reason to write it this way at one point in time I guess (maybe related to reading from stdin).

Anyway here is the fix: https://github.com/svenvc/zinc/commit/66612d464b73f3537badb7e4d178672888ced3a1

Sven

**Comment by jbrichau** [comment]
thanks for the quick response @svenvc !
