### ISSUE TITLE
Problem with asZnUrl on Windows System

### ISSUE THREAD

**Issue by DelGaylord** [svenvc/zinc#92]
To explain it a little better, i am currently working on Microdown, a new markdown more simple but more extensible.
In my task, i use asZnUrl in one of my method but i got %C5 instead of / like the screenshot below. 
@kasperosterbye
![ErrorOnWindows](https://user-images.githubusercontent.com/60885865/165753253-d23d2b13-8092-440b-9fb0-5d254c88a1ff.PNG)

**Comment by kasperosterbye** [comment]
@svenvc - would the above be true also for windows? If so, I am using a wrong method call somewhere inside MicResourceReference (which I am responsible for).

**Comment by kasperosterbye** [comment]
In that case (@svenvc and @DelGaylord) the error is mine and is hiding somewhere in the resolver I built. Thanks for your responses.
I suggest @DelGaylord to close this issue as it is not a Zinc issue...
