### ISSUE TITLE
ZnUTF8Encoder does not signal error when decoding #[16rF4 16r90 16r80 16r80]

### ISSUE THREAD

**Issue by Rinzwind** [svenvc/zinc#96]
In the following example, the `#decodeBytes:` message returns a String that cannot be encoded by `#encodeString:`:

```smalltalk
string := ZnCharacterEncoder utf8 decodeBytes: #[16rF4 16r90 16r80 16r80].
"⇒ string is equal to: (String with: (Character codePoint: 16r110000))"

ZnCharacterEncoder utf8 encodeString: string
"⇒ signals ZnInvalidUTF8: Character Unicode code point outside encoder range"
```

I think the `#decodeBytes:` message should already have signaled an error, as the byte sequence is not a well-formed UTF-8 byte sequence according to table 3-7 on p. 124 in section ‘3.9 Unicode Encoding Forms’ of [‘The Unicode Standard, Version 14.0 – Core Specification’](https://www.unicode.org/versions/Unicode14.0.0/). As the first byte is F4, the second byte should be in the range 80..8F to be part of a well-formed sequence.

**Comment by svenvc** [comment]
Thanks a lot for the feedback, the following commit should fix your issue:

https://github.com/svenvc/zinc/commit/37b7d0f83835520efbde74be65fef35ebc308b95

Can you check ?

**Comment by Rinzwind** [comment]
Looks OK, thanks!

BTW, maybe take a look at [PTermUTF8Encoder](https://github.com/lxsang/PTerm/blob/1856f167ef013c24f41251707d96259039b5e012/PTerm-Core/PTermUTF8Encoder.class.st), it might make sense to pull up the method `#decodeStreamUpToIncomplete:` to ZnUTF8Encoder. It decodes a stream of bytes, while offering two ‘conveniences’: substituting U+FFFD for invalid subsequences, and resetting the stream to the position before an incomplete subsequence at the end (if there is one). There’s a test in [PTermUTF8EncoderTest](https://github.com/lxsang/PTerm/blob/1856f167ef013c24f41251707d96259039b5e012/PTerm-Test/PTermUTF8EncoderTest.class.st). It’s used to handle output like in this example (from https://github.com/lxsang/PTerm/issues/28):

<img width="486" alt="Example PTermUTF8Encoder" src="https://user-images.githubusercontent.com/1611248/174388258-c6bfdbca-c64f-4e59-a3b7-770c1285685c.png">
